name: Choice
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - debug
          - info
          - warning
          - error
        description: "Log level"
jobs: # ジョブの定義
  run: # ジョブ名/ID
    runs-on: ubuntu-latest # 実行環境
    steps: # ステップの定義
      - run: echo "${{ inputs.log-level }}" # ステップの実行内容
