name: Context
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "actor ${{ github.actor }} \n
          run_id ${{ github.run_id }} \n
          sha ${{ github.sha }} \n
          ref ${{ github.ref }} \n
          event ${{ github.event_name }} \n
          repo ${{ github.repository }} \n
          workspace ${{ github.workspace }} \n
          action ${{ github.action }} \n
          job ${{ github.job }} \n
          workflow ${{ github.workflow }} \n
          action ${{ github.action }} \n
          event ${{ github.event }} \n
          event_path ${{ github.event_path }} \n
          event_name ${{ github.event_name }} \n
          ランナーのコンテキスト \n
          runner ${{ runner.name }} \n
          runner_os ${{ runner.os }} \n
          runner_temp ${{ runner.temp }} \n
          runner_arch ${{ runner.arch }} \n
          runner_tool_cache ${{ runner.tool_cache }} \n
          runner_workspace ${{ runner.workspace }} \n
          runner_debug ${{ runner.debug }} \n"
